"whose handbag is it ?"
"Excuse me!"
"Yes?"
"Is this your handbag ?"
"Pardon?"
"Is this your handbag ?"
"Yes,it is."
"Thank you very much."

"Does the man get his umbrella back?"
"My coat and My umbrella please."
"Here's my ticket."
"Thank  you sir."
"Here is your umbrella and your coat."
"This is not my umbrella ."
"Sorry sir."
"Is this your umbrella?"
"No,it isn't."
"Is this it?"
"Yes, it is."
"Thank you very much."